#!/usr/bin/env ansible-playbook
---
- name: Add ansible user
  remote_user: root
  hosts: debian
  tags: always
  become: true
  roles:
    - ansible_user
- name: Install necessary software for debian hosts
  hosts: debian
  remote_user: ansible
  become: true
  roles:
    - software_debian
