---
- name: Install web server
  hosts: all
  become: true
  tasks:
    - name: Update repository index
      ansible.builtin.apt:
        update_cache: true
    - name: Install apache2 package
      ansible.builtin.apt:
        name: apache2
    - name: Install pehope
      ansible.builtin.apt:
        name: libapache2-mod-php
