#!/usr/bin/env ansible-playbook
- name: Add ansible user
  hosts: nfsservers
  tags: always
  remote_user: root
  roles:
    - ansible_user
- name: Install necessary software for debian hosts
  hosts: debian
  remote_user: ansible
  become: true
  roles:
    - software_debian
- name: Install nfs server storage
  remote_user: ansible
  hosts: nfs_servers
  become: true
  roles:
    - nfs
