#!/usr/bin/env ansible-playbook
- name: Add ansible user
  hosts: proxmox
  remote_user: root
  roles:
    - ansible_user
- name: Proxmox initial configuration
  hosts: proxmox
  remote_user: root
  roles:
    - proxmox_init
- name: Proxmox normal configuration
  hosts: proxmox
  remote_user: ansible
  become: true
  roles:
    - proxmox_config
