---
- name: Get cloudimage filename (debian)
  when: cloudimage_distro == "debian"
  block:
    - name: Get cloud image versions
      ansible.builtin.uri:
        url: "{{ cloudimage_repo_url }}"
        return_content: true
      register: cloudimage_versions_page
      when: cloudimage_release == "latest"

    - name: Parse latest cloud image version
      ansible.builtin.set_fact:
        cloudimage_release: >-
          {{ cloudimage_versions_page.content.split('</tr>') |
          map('regex_search', '<a href="(\d{8}-\d+)/">', '\1') |
          select() | map('first') | list | last }}
      when: cloudimage_release == "latest"

    - name: Get cloud image urls
      ansible.builtin.uri:
        url: "{{ cloudimage_repo_url }}{{ cloudimage_release }}/"
        return_content: true
      register: cloudimage_images_page

    - name: Set cloudimage filename
      ansible.builtin.set_fact:
        cloudimage_filename: >-
          {{ cloudimage_images_page.content.split('\n') |
          map('regex_search', '<a href="([^\"]*-%s-(daily-)?%s.%s)">' %
            (cloudimage_type, cloudimage_release, cloudimage_format), '\1')
          | select() | first | first }}

- name: Get cloudimage filename (ubuntu)
  when: cloudimage_distro == "ubuntu"
  block:
    - name: Set cloudimage filename
      ansible.builtin.set_fact:
        cloudimage_filename: "{{ cloudimage_repo_subdir + '-' + cloudimage_type + '.' + cloudimage_format }}"

    - name: Get cloudimage releasedate
      when: cloudimage_release == "current"
      ansible.builtin.uri:
        url: "{{ cloudimage_repo_url }}"
        return_content: true
      register: cloudimage_versions_page

    - name: Parse latest ubuntu cloud image version
      when: cloudimage_release == "current"
      ansible.builtin.set_fact:
        cloudimage_release: >-
          {{ cloudimage_versions_page.content.split('<a href') |
          map('regex_search', '^=\"(\d{8})/\">', '\1') |
          select() | map('first') | list | last }}

- name: Construct cloudimage url
  ansible.builtin.set_fact:
    cloudimage_url: >-
      {{ cloudimage_repo_url }}{{ cloudimage_release }}/{{ cloudimage_filename }}
