---
- name: Get cloudimage checksums
  ansible.builtin.uri:
    url: "{{ cloudimage_repo_url }}{{ cloudimage_release }}/{{ cloudimage_hashtype | upper }}SUMS"
    return_content: true
  register: cloudimage_checksums_file

- name: Parse cloud image checksum
  ansible.builtin.set_fact:
    cloudimage_checksum: >-
      {{ cloudimage_checksums_file.content.split('\n') |
      map('regex_search', '(\w+) [ \*]%s' % cloudimage_filename, '\1') |
      select() | first | first }}
