- name: Remove enterprise bloat
  ansible.builtin.import_tasks: fix_enterprise_repo.yml
- name: Fix home permissions
  ansible.builtin.file:
    path: /home/ansible
    state: directory
    recurse: true
    owner: ansible
    group: ansible
- name: Fix .bashrc config
  ansible.builtin.copy:
    src: .bashrc
    dest: /root/
    owner: root
    group: root
    mode: "0644"
- name: Fix .bashrc config
  ansible.builtin.copy:
    src: .bashrc
    dest: /home/ansible/
    owner: ansible
    group: ansible
    mode: "0644"
- name: Install software
  ansible.builtin.import_tasks: software.yml
