---
- name: Install updates
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
- name: Install basic software
  tags: always
  ansible.builtin.apt:
    name:
      - btop
      - curl
      - efibootmgr
      - git
      - htop
      - jq
      - kpartx
      - neovim
      - parted
      - sudo
      - tmux
      - wget
      - yq
- name: Install BootNext
  ansible.builtin.get_url:
    validate_certs: false
    url: "https://github.com/TensorWorks/bootnext/releases/download/v0.0.2/bootnext-linux-amd64"
    dest: "/usr/local/bin/bootnext"
    mode: "0755"
