---
- name: Install updates
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
- name: Install basic software
  tags: always
  ansible.builtin.apt:
    name:
      - sudo
      - parted
      - kpartx
      - jq
      - yq
      - htop
      - btop
      - curl
      - wget
      - tmux
      - neovim
      - git
