- name: Add qemu vm
  block:
    - name: Cluster NextID
      ansible.builtin.command: pvesh get /cluster/nextid
      changed_when: false
      register: nextid
    - name: Set node facts
      ansible.builtin.set_fact:
        next_vm_id: "{{ nextid.stdout }}"
        node_hostname: "k8s-{{ item }}-{{ nextid.stdout }}.srv"
    - name: Create {{ node_hostname }}
      register: create_node_cmd
      changed_when: create_node_cmd.rc == 0
      failed_when: create_node_cmd.rc > 0
      ansible.builtin.command: qm clone 100 {{ nextid.stdout }} --name {{ node_hostname }}
    - name: Add hook script to {{ node_hostname }}
      ansible.builtin.template:
        src: "hook.j2"
        dest: "{{ snippet_storage_path }}/{{ node_hostname }}.sh"
        owner: ansible
        group: ansible
        mode: "0755"
    - name: Set hook-script {{ node_hostname }}
      register: qm_set_hook_script
      changed_when: qm_set_hook_script.rc == 0
      failed_when: qm_set_hook_script.rc > 0
      ansible.builtin.command: >-
        qm set {{ next_vm_id }} -hookscript {{ local_storage_name }}:snippets/{{ node_hostname }}.sh
    - name: Start {{ node_hostname }}
      register: start01
      changed_when: start01.rc == 0
      failed_when: start01.rc > 0
      ansible.builtin.command: qm start {{ next_vm_id }}
