- name: Import distro specific vars
  ansible.builtin.include_vars:
    file: "vars/proxmox.yml"
- name: Configure the Proxmox
  ansible.builtin.import_tasks: proxmox-configure.yml
- name: Template facts
  ansible.builtin.set_fact:
    local_storage_name: "local"
- name: Snippet storage fs path
  changed_when: false
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      pvesh get /storage/{{ local_storage_name }} --output-format json | jq -r .path
    executable: /bin/bash
  register: local_storage_path
- name: Set fact
  ansible.builtin.set_fact:
    snippet_storage_path: "{{ local_storage_path.stdout }}/snippets"
- name: Create the debian vm template
  ansible.builtin.import_tasks: debian-vm-template.yml
- name: Create debian qemu virtual machines
  ansible.builtin.include_tasks: debian-qemu-vms.yml
  loop:
    - node
    - node
    - node
    - management
